### ISSUE TITLE
Question about install

### ISSUE THREAD

**Issue by LaterBetterThanNever** [zjhch123/GithubStatus3#9]
Hey, it's really cool and I wonder how to install on MacOS?
Thanks for reply.

**Comment by zjhch123** [comment]
Let's download the App from the [release page](https://github.com/zjhch123/GithubStatus3/releases). Thanks!

**Comment by LaterBetterThanNever** [comment]
Thanks for reply, I also get a question: the app doesn't show the correct data about my commits, it's not same as my github overview.
What should I do?

**Comment by zjhch123** [comment]
> Thanks for reply, I also get a question: the app doesn't show the correct data about my commits, it's not same as my github overview.
> What should I do?

Do you have any screenshot? I thought the data must be the same as your [Github profile page](https://github.com/LaterBetterThanNever).

**Comment by LaterBetterThanNever** [comment]
Here’re the screenshots.Thanks.




On 02/3/2020 10:48，Jiahao.Zhang<notifications@github.com> wrote：

Reopened #9.

**Comment by zjhch123** [comment]
Sorry but I can't see your screenshot

**Comment by LaterBetterThanNever** [comment]
Is that OK?




On 02/3/2020 15:29，Jiahao.Zhang<notifications@github.com> wrote：

Sorry but I can't see your screenshot

**Comment by zjhch123** [comment]
Sorry..

![image](https://user-images.githubusercontent.com/12215513/73633755-6d3f6300-469a-11ea-9be0-f3f2cbafcb80.png)

**Comment by LaterBetterThanNever** [comment]
Sorry about that, may I have your personal e-mail address, please?


On 02/3/2020 15:33，Jiahao.Zhang<notifications@github.com> wrote：

Sorry..

**Comment by zjhch123** [comment]
Sure, zjhch123@gmail.com

**Comment by zjhch123** [comment]
Hi, I got your snapshot and did some investigation.

The App will send the request directly to your profile page without any states (cookie, session and etc..) for fetching the commits, which means the data will be the same as your non-login profile page.

Maybe you should update your privacy settings for showing all of your commits on your profile page.

**Comment by LaterBetterThanNever** [comment]
Thanks so much.




On 02/5/2020 19:00，Jiahao.Zhang<notifications@github.com> wrote：

Hi, I got your snapshot and do some investigation.

The App will send the request directly to your profile page without any states (cookie, session and etc..) for fetching the commits, which means the data will be the same as your non-login profile page.

Maybe you should update your privacy settings for showing all of your commits on your profile page.
